### ISSUE TITLE
Failing to call CMD commands when INITSYSTEM=on

### ISSUE THREAD

**Issue by ntzovanis** [balena-io-library/base-images#226]
When using resin/odroid-ux3-python:latest

If on DOCKERFILE:
```
INITSYSTEM=on
CMD bash start.sh
```
then start.sh is not executed (it's only executed if called as ```ENTRYPOINT bash start.sh```)

If on DOCKERFILE:
```
INITSYSTEM=off
CMD bash start.sh
```
then start.sh is exectuted

**Comment by shaunmulligan** [comment]
@ntzovanis one clarification, this is on resinOS (unmanaged) when one does `rdt push`, correct?

**Comment by ntzovanis** [comment]
@shaunmulligan that's correct

**Comment by shaunmulligan** [comment]
@petrosagg or @nghiant2710 any ideas on why this would happen?

**Comment by nghiant2710** [comment]
@ntzovanis can you please send us the Dockerfile? I can't reproduce your issue, it seems fine on my side

**Comment by shaunmulligan** [comment]
@nghiant2710 did you try reproduce this on pure resinOS with `rdt` ... the issue only appears there and not on resin.io

**Comment by ntzovanis** [comment]
@shaunmulligan is right. The issue happens on pure resinOS (and rdt). I've tried it in different computers and odroids with the same result.

```FROM resin/odroid-ux3-python:latest

# Enable systemd
ENV INITSYSTEM on

ENV PYTHONUNBUFFERED=0

# Your code goes here

WORKDIR /usr/src/mqtt-client

COPY . .

RUN pip install paho-mqtt
RUN pip install requests
RUN pip install pytz


ENTRYPOINT bash start.sh```

Where start.sh can be anything and it's not called at all.
