### ISSUE TITLE
Python stretch images

### ISSUE THREAD

**Issue by FRVisser** [balena-io-library/base-images#439]
Hey, 

We run in some issues with the git version and this would be solved if we could use debian stretch images. I see stretch dockerfiles but there aren't any tags to use it. 

We would like to use a 3.6 slim stretch image. Is the release of stretch in the pipeline?

Thanks!

**Comment by FluxReality** [comment]
@nghiant2710 are there any updates on this?

Much in need for stretch images of python.

**Comment by nghiant2710** [comment]
@FRVisser @FluxReality there is a `3.7-stretch` image that you can use now. We have a little issue with other versions due to a new OpenSSL version on Debian Stretch (we're compiling all the binaries on Debian Jessie and they won't work on Stretch) so support for other versions will be added later.

**Comment by FRVisser** [comment]
I works like a dream. However, I have one more request: We used to use the 3-slim image because of its small size. The bare size difference is now 226 Mb for the old 3-slim image and 790 Mb for the new stretch image. 

Any change there will be stretch-slim image available in the future?

**Comment by nghiant2710** [comment]
@FRVisser regarding your requests here, I guess you will love the new balenalib base images

**Comment by FRVisser** [comment]
@nghiant2710 71 MB 😱 What secret lies beneath this beautiful number?
