### ISSUE TITLE
Alpine-python base image fails to find pip-installed package

### ISSUE THREAD

**Issue by gregorybodnar** [balena-io-library/base-images#461]
I was starting with the trivial python flask server example on a 2GB Beaglebone Black. Since there seems to be an issue with the systemd init in the current debian image, I tried the resin/beaglebone-black-alpine-python image. The python script failed with the following:

> 19.08.18 17:33:12 (+1200)  main   * Starting Resin.io User Application ...
> 19.08.18 17:33:14 (+1200)  main  Traceback (most recent call last):
> 19.08.18 17:33:14 (+1200)  main    File "src/main.py", line 1, in <module>
> 19.08.18 17:33:14 (+1200)  main      from flask import Flask
> 19.08.18 17:33:14 (+1200)  main  ImportError: No module named flask
> 19.08.18 19:22:49 (+1200)  main   * Stopping Resin.io User Application ...

I could ssh into the container and import flask from a python REPL, so I had the script spit out the entries in sys.path. The list included the app path (/usr/src/app) as well as the tree of paths starting at /usr/lib/python2.7. Flask was installed by pip

 into /usr/local/lib/python2.7/site-packages, but this path was not available to python when the container entry point was run. I was able to work around this by setting PYTHONPATH from the resin.io interface as a quick test.

My assumption is that running pip within the Dockerfile should give me a working environment for python executed from the same Dockerfile. It would be extra friction to require pip to be called with a -t option to force packages into the right place.

**Comment by nghiant2710** [comment]
This issue was fixed in balenalib base images.
