### ISSUE TITLE
entry.sh double-escapes ENV vars

### ISSUE THREAD

**Issue by wrboyce** [balena-io-library/base-images#477]
`printf '%q="%q"\n' "$var" "${!var}"`

both `%q` and quotes are unnecessary and result in double-escaping.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gwmr)

**Comment by spiderkeys** [comment]
@wrboyce The change in your merged PR has resulted in the values in /etc/docker.env becoming no longer double quoted.

This has gone back and forth over several months between having the /etc/docker.env values being not double quoted, then double quoted, and now not again, causing unexpected failures in our software thrice. If the variables are not double quoted, then the env file cannot be sourced, so the double quotes were a welcome change. Can we please stabilize the decision around this?

**Comment by nghiant2710** [comment]
hey @spiderkeys, sorry for the late response, it seems the docker.env like how it is now (the one in the latest image like `resin/armv7hf-debian:jessie`) can be sourced properly. Can you please explain how is your script broken?
