### ISSUE TITLE
build instructions / keeping up with releases

### ISSUE THREAD

**Issue by timcoote** [balena-io-library/base-images#481]
I'm trialling some python 3.7 code on aarch64 devices (fedora 29 iot). I've used the docker images for building for Raspbian on aws, which works well.

From a production point of view, Fedora's much closer to the current releases of most packages than many other distros, and RH is putting effort into supporting small, standalone computers.

So this is a plea, either to build the more recent fedora images, or docker images that support python 3.7 on aarch, or to point me at how to build such images (I have tried hard to find this in the documnetation, but failed miserably).

**Comment by nghiant2710** [comment]
Hey @timcoote, please have a look at our document here https://www.balena.io/docs/reference/base-images/base-images/, I think we do have all the images mentioned above.
