### ISSUE TITLE
Add docker image for raspberry-pi node v10 (LTS)

### ISSUE THREAD

**Issue by feluelle** [balena-io-library/base-images#489]
As of [nodejs offcial site](https://nodejs.org/en/) the current LTS changed from version 8 to 10.

It would be great if we could have a **raspberry-pi** docker image for this release. :)

**Comment by nghiant2710** [comment]
@feluelle you can try `resin/raspberry-pi-node` image, it currently points to node `v.10.9.0`

Since we're busy with moving `resin` base images to new namespace `balenalib` with a lot of changes so our node images are not up to date with latest node versions, sorry for the inconvenience.

**Comment by feluelle** [comment]
Thank you @nghiant2710. Is it possible to use the v10 tag? Because on the docker hub for `resin/raspberry-pi-node` I can not find a tag for any v10 release. I do not want to use `latest` or whatever it is currently pointing to, actually :/

**Comment by nghiant2710** [comment]
@feluelle  Of course, there is a `resin/raspberry-pi-node:10` image (it's currently latest), docker hub doesn't show all the tags so you can't find `v10` there. It's better to check docker store https://store.docker.com/community/images/resin/raspberry-pi-node/tags

**Comment by feluelle** [comment]
That works, thank you.
