### ISSUE TITLE
intel-edison-golang:1.11-build doesn't have required build dependencies

### ISSUE THREAD

**Issue by imrehg** [balena-io-library/base-images#511]
Found it by building some go code, that worked on `...-golang:1.11-build`  for the NUC, RPi3, ARTIK710, but  when used with Edison, it complains of `gcc` and `make` not being available, etc..... The build succeeded after installing the `build-essential` package, but it should be present, I believe?

Not sure if other language or tag for the Edison is affected.

**Comment by imrehg** [comment]
Thanks a lot!

**Comment by nghiant2710** [comment]
@imrehg, It's fixed in https://github.com/balena-io-library/base-images/pull/514
