### ISSUE TITLE
Cross build fails when upgrade balenalib/raspberry-pi-debian-node

### ISSUE THREAD

**Issue by laseryuan** [balena-io-library/base-images#522]
When upgrade the base image from "balenalib/raspberry-pi-debian-node:9.11.2-stretch-build-20181207" to "lbalenalib/raspberry-pi-debian-node:10.15-stretch-build-20190127" I got below error message. It looks like related with cross building. Same error applies to "balenalib/raspberry-pi-debian-node:10.14.0-stretch-build-20181207"
```
Unsupported ioctl: cmd=0x40049409                               
Unsupported ioctl: cmd=0x40049409                        
Unsupported ioctl: cmd=0x40049409                                  
Unsupported ioctl: cmd=0x40049409                             
Unsupported ioctl: cmd=0x40049409                               
Unsupported ioctl: cmd=0x40049409                                  
error An unexpected error occurred: "ENOSYS: function not implemented, copyfile '/home/node/.cache/yarn/v4/npm-abab-2.
0.0-aba0ab4c5eee2d4c79d3487d85450fb2376ebb0f/node_modules/abab/LICENSE.md' -> '/node_modules/abab/LICENSE.md'".
```

**Comment by nghiant2710** [comment]
@laseryuan, the images you mentioned have the same cross-build implementation so I'm not sure if it's a cross-build issue. Since you change the nodejs major version from v9.x to v10.x, could it be the problem?
