### ISSUE TITLE
libraspberrypi-bin missing from raspberry-pi image

### ISSUE THREAD

**Issue by chrisys** [balena-io-library/base-images#543]
Referencing [this](https://forums.balena.io/t/raspberry-pi-zero-debian-node-image-does-not-include-raspistill-camera-executable/6406/) forum thread, the user reported that the `raspistill` binary is missing from `raspberry-pi` base images but is present in `raspberrypi3` images. Installing the `libraspberrypi-bin` package manually worked for them, but it was an obstruction to find that it was missing and deal with it separately. 

Shown missing [here](https://github.com/balena-io-library/base-images/blob/master/balena-base-images/device-base/raspberry-pi/debian/stretch/run/Dockerfile) (raspberry-pi)
Present [here](https://github.com/balena-io-library/base-images/blob/master/balena-base-images/device-base/raspberrypi3/debian/stretch/run/Dockerfile) (raspberrypi3)

**Comment by nghiant2710** [comment]
Fixed here https://github.com/balena-io-library/resin-rpi-raspbian/commit/31f886bcd1353d087f3830ce1b50a57559f31206.

For some reason, `libraspberrypi-bin` is no longer added by default when we debootstrap the image (it was), so we have to manually install it later in the Dockerfile.
