### ISSUE TITLE
Add support for missing tag balenalib/raspberrypi3-debian-node:10.16-buster

### ISSUE THREAD

**Issue by FedericoPonzi** [balena-io-library/base-images#555]
Hello,
As per title, right now the tag for `balenalib/raspberrypi3-debian-node:10.16-buster` is missing.
Since I can see the Dockerfile in https://github.com/balena-io-library/base-images/tree/master/balena-base-images/node/raspberrypi3/debian/buster I think it might be needed some wiring up between github & docker hub.
Thanks!

**Comment by lurch** [comment]
https://registry.hub.docker.com/layers/balenalib/raspberrypi3-debian-node/10.16-buster/images/sha256-022ad412ea5ce926fac76d6b5d2750758484a9810ea7b3f892a89b26d47a2dc2
:question:

**Comment by nghiant2710** [comment]
Closing as the image is available.
