### ISSUE TITLE
balenalib/raspberry-pi:buster missing chromium-browser ?

### ISSUE THREAD

**Issue by alexzace** [balena-io-library/base-images#558]
`apt-get install chromium-browser`

Package 'chromium-browser' has no installation candidate 

Please help on this problem . thanks

**Comment by nghiant2710** [comment]
Hey @alexzace, thank you for the report, the fix for this will be released soon, you can add the below lines in your Dockerfile as a workaround for now.
```
RUN echo "deb http://archive.raspberrypi.org/debian buster main ui" >>  "/etc/apt/sources.list.d/raspi.list"
RUN apt-key adv --batch --keyserver ha.pool.sks-keyservers.net  --recv-key 0x82B129927FA3303E
```

**Comment by alexzace** [comment]
@nghiant2710  thanks
