### ISSUE TITLE
aarch64-debian-dotnet:3.1 not found

### ISSUE THREAD

**Issue by gerb0n** [balena-io-library/base-images#610]
Hi,

When browsing through the repo I can find the [dotnet 3.1 images](https://github.com/balena-io-library/base-images/tree/master/balena-base-images/dotnet/aarch64/debian/buster).

However when I'm using it inside a Dockerfile it says '**not found**' / '**manifest unknown**'.

What works: `FROM balenalib/aarch64-debian-dotnet:3.0-sdk`
What doesn't work: `FROM balenalib/aarch64-debian-dotnet:3.1-sdk`

It doesn't work for **runtime** or **aspnet** either.

**Comment by nghiant2710** [comment]
@gerb0n, we're working on it, will let you know when the base images are ready

**Comment by nghiant2710** [comment]
@gerb0n just want to let you know that the dotnet base image 3.1 are ready, please let us know if you need further support.
