### ISSUE TITLE
Add coral sources to debian images

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io-library/base-images#627]
We should add the coral sources to our coral base images (debian for sure, but maybe even ubuntu?) 

Basically for the default debian images we should have:
```
# Add Google Coral sources lists
RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

# udev in the container to enable TPU correctly
ENV UDEV=1
COPY 99-tpu.rules /etc/udev/rules.d/99-tpu.rules
```

For the python images we should have:
```
# Install the TPU packages we will need
RUN install_packages libedgetpu1-std \
            libedgetpu-dev \
            python3-edgetpu \
            edgetpu-examples \
            python3-pip
```

the `99-tpu.rules` rules should contain:
```
"SUBSYSTEM=="usb",ATTRS{idVendor}=="1a6e",GROUP="plugdev" 
"SUBSYSTEM=="usb",ATTRS{idVendor}=="18d1",GROUP="plugdev"
```

**Comment by nghiant2710** [comment]
hey @shaunmulligan, I think we should install all the packages marked as pre-installed here https://coral.ai/software/#debian-packages.

About `edgetpu-examples`, it contains the examples only so not sure if we should install it by default, maybe users should install it manually if needed

**Comment by shaunmulligan** [comment]
@nghiant2710 yeah I agree!

**Comment by nghiant2710** [comment]
Fixed in https://github.com/balena-io/contracts/commit/c621038eeb2cafd2fa68f5b3234ebd78b0062849
