### ISSUE TITLE
manifest for balenalib/raspberrypi3-ubuntu-node:latest-focal not found

### ISSUE THREAD

**Issue by timelapsepaul** [balena-io-library/base-images#640]
How can install using the ubuntu focal image with the latest version of nodejs?

**Comment by nghiant2710** [comment]
Hi @timelapsepaul, looks like this image is missing, I will check our build servers and get back to you with more details as soon as possible

**Comment by nghiant2710** [comment]
@timelapsepaul, just want to let you know that the `balenalib/raspberrypi3-ubuntu-node:latest-focal` base image is available. Please let us know if you need further support.
