### ISSUE TITLE
Unable to run balenalib/raspberry-pi-debian:buster-build on Ubuntu 18.04

### ISSUE THREAD

**Issue by dave-malone** [balena-io-library/base-images#662]
After pulling the image, I attempted to run the image via `sudo docker run -it balenalib/raspberry-pi-debian:buster-build /bin/bash` and I received the following error: 

`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by moncio** [comment]
How did you solve this issue? I have the same one @dave-malone
