### ISSUE TITLE
balena host OS consuming ~50% of memory by itself?

### ISSUE THREAD

**Issue by ealmonte32** [balena-io-library/base-images#663]
Is it just me or is anyone else experiencing the host OS taking up as much as 50% of the memory of the raspberry pi device even when all the containers/services are stopped?
Can I disable that "experimental" log driver flag? seems like that is taking up a lot of the memory.. I do need to see the logs of course, I just dont think that is normal to be consuming so much memory.

![Screen Shot 2020-10-06 exp balena](https://user-images.githubusercontent.com/24350198/95373622-4087bf00-08ab-11eb-8ccc-33eb8537d82f.png)
![Screen Shot 2020-10-06 at 2 56 09 PM](https://user-images.githubusercontent.com/24350198/95373626-41205580-08ab-11eb-9ad2-94f7a515a61b.png)
![Screen Shot 2020-10-06 at 2 56 02 PM](https://user-images.githubusercontent.com/24350198/95373628-41205580-08ab-11eb-94d5-a1502313bd2e.png)

**Comment by nghiant2710** [comment]
hi @ealmonte32, can you please bring this issue to our support on balena dashboard or balena forums (https://forums.balena.io/) and our support agent will be happy to help?

Since this is Docker base-images repository so we only handle base-images related issue.
