### ISSUE TITLE
Release base images with Alpine 3.12.3

### ISSUE THREAD

**Issue by xginn8** [balena-io-library/base-images#673]
This version was released 12/16/2020.

**Comment by tmigone** [comment]
I think we can close this one. We don't have tags for specific patch versions but using `FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.12-run` as of today will get you `v3.12.6`

```
bash-5.0# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.6
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by tmigone** [comment]
cc @nghiant2710
