### ISSUE TITLE
balenalib/raspberrypi4-64-golang:1.16 images missing

### ISSUE THREAD

**Issue by rickardgranberg** [balena-io-library/base-images#687]
Can't find any Go 1.16 images on Docker hub.

I can find Dockerfile(s) here for all distros with Go 1.16 in them, for example: https://github.com/balena-io-library/base-images/blob/master/balena-base-images/golang/raspberrypi4-64/debian/buster/1.16/build/Dockerfile

This same problem happened for 1.15 images iirc.

**Comment by rblenkinsopp** [comment]
They are also missing for the `raspberry-pi` (v1 & zero) architectures.

**Comment by paulburlumi** [comment]
Fixed?
https://github.com/balena-io-library/base-images/blob/master/balena-base-images/golang/raspberrypi4-64/debian/buster/1.16.7/build/Dockerfile

**Comment by rickardgranberg** [comment]
> Fixed?
> https://github.com/balena-io-library/base-images/blob/master/balena-base-images/golang/raspberrypi4-64/debian/buster/1.16.7/build/Dockerfile

No, the problem is that the images does not exist on Docker Hub. For some reason they aren't pushed...

**Comment by nghiant2710** [comment]
Hi all, thank you for the report, we acknowledged the issue and will add the missing base-images soon.
I will let you know when they are available.

**Comment by nghiant2710** [comment]
Just want to let you know that the Go v1.16 and v1.17 base images are now available, please let us know if you need further support.
