### ISSUE TITLE
missing raspberrypicm4-ioboard images

### ISSUE THREAD

**Issue by klutchell** [balena-io-library/base-images#690]

**Comment by jhancharler** [comment]
Are there any updates on this?

An ETA on when the images are to be provided?

`manifest for balenalib/raspberrypicm4-ioboard-alpine-node:10-stretch-run not found: manifest unknown: manifest unknown`

**Comment by nghiant2710** [comment]
hey @jhancharler, you are requesting a Debian tag `10-stretch-run` in a Alpine Linux base image `balenalib/raspberrypicm4-ioboard-alpine-node` so that's why the tag is missing. Can you fix the image you want to use and try again?
