### ISSUE TITLE
Images on Docker Hub have incorrect architecture (amd64)

### ISSUE THREAD

**Issue by nghiant2710** [balena-io-library/base-images#692]

**Comment by Mausy5043** [comment]
Not everybody has access to jellyfish.For those googling for this issue and to prevent

**Comment by alanb128** [comment]
@nghiant2710 I recently checked for a user and the architecture on the base images I inspected appear to be correct now, so does that mean this issue can be closed?

**Comment by nghiant2710** [comment]
@alanb128, ah yes, the architecture in our base images are correct now so this can be closed.
