### ISSUE TITLE
Missing Base Images for some Architectures

### ISSUE THREAD

**Issue by dtischler** [balena-io-library/base-images#696]
@nghiant2710 Can you help shed some light on why some Base images don't exist for all architectures?  Here is an example: 

Available:

```balenalib/aarch64-alpine-node:14.16-3.13-build
balenalib/armv7hf-alpine-node:14.16-3.13-build
```

Not available:

```
balenalib/armv6hf-alpine-node:14.16-3.13-build
balenalib/amd64-alpine-node:14.16-3.13-build
```

And, could we please have those `alpine-node:14.16-3.13-build` created for armv6 and amd64, please?   :-)

**Comment by dtischler** [comment]
cc:  @ maggie0002

**Comment by maggie0002** [comment]
Another one.

Available:

balenalib/amd64-alpine-python:3.8.10-3.13

Not available:

balenalib/raspberrypi4-64-alpine-python:3.8.10-3.13

**Comment by maggie0002** [comment]
Linked issue on Balena Forums for reference: https://forums.balena.io/t/missing-images-from-balenalib/319708/8

**Comment by wrobell** [comment]
Similar to #686.

**Comment by maggie0002** [comment]
> Similar to #686.

And I think other similar posts:

https://github.com/balena-io-library/base-images/issues/695
https://github.com/balena-io-library/base-images/issues/691
https://github.com/balena-io-library/base-images/issues/687
https://github.com/balena-io-library/base-images/issues/680
https://github.com/balena-io-library/base-images/issues/661
https://github.com/balena-io-library/base-images/issues/606
https://github.com/balena-io-library/base-images/issues/602

**Comment by nghiant2710** [comment]
Hey @maggie0002, just want to let know that all the images you mentioned are now available. So sorry for the inconvenience, I will work on other issues as well and keep this issue open so everyone can report if there is a missing tag and we will try to resolve as soon as possible.

**Comment by zartdinov** [comment]
@nghiant2710 Hi! I can't find tag for this Dockerfile:
https://github.com/balena-io-library/base-images/blob/master/balena-base-images/python/raspberrypi4-64/debian/bullseye/3.9.7/build/Dockerfile
