### ISSUE TITLE
Java 16 images

### ISSUE THREAD

**Issue by AlexProgrammerDE** [balena-io-library/base-images#701]
Hi there! I would like to suggest Java 16 images to be an option to choose. I need it in my project [balena-minecraft-server](https://github.com/AlexProgrammerDE/balena-minecraft-server) as Java 16 is now an official requirement to get the server software working on 1.17. Should hopefully not be too hard as Java 8 and 11 images already exist. Thanks!

**Comment by nghiant2710** [comment]
hey @AlexProgrammerDE just want to let you know that the openjdk 16 (JDK) base images for amd64 and aarch64 devices are available.

**Comment by AlexProgrammerDE** [comment]
Hi @nghiant2710 could these images also get published for the specific device types? That is what my fleet is relying on at the moment.

**Comment by nghiant2710** [comment]
@AlexProgrammerDE what are you target device types? `amd64 and aarch64 devices` mean all specific devices with amd64/aarch64 architecture will have openJDK 16 base images

**Comment by AlexProgrammerDE** [comment]
@nghiant2710 according to dockerhub the last update for raspberrypi4-64 was 5 months ago: https://hub.docker.com/r/balenalib/raspberrypi4-64-debian-openjdk/tags?page=1&ordering=last_updated

**Comment by nghiant2710** [comment]
@AlexProgrammerDE, I will check our build servers to see if anything is wrong but the PR was merged last week so it should be available now.

**Comment by nghiant2710** [comment]
@AlexProgrammerDE, I restarted the builds, the openJDK 16 images should be there, Can you give it a try?

**Comment by AlexProgrammerDE** [comment]
@nghiant2710 I just pushed successfully to my fleet. Seems to work fine. Thanks!
