### ISSUE TITLE
raspberrypi4-64-python Ubuntu Focal images missing

### ISSUE THREAD

**Issue by mrts** [balena-io-library/base-images#703]
When I look at tags in https://hub.docker.com/r/balenalib/raspberrypi4-64-python/tags, I don't see Ubuntu Focal images, although [docs](https://www.balena.io/docs/reference/base-images/base-images/) mention Focal and the Dockerfiles are available in [the current repository](https://github.com/balena-io-library/base-images/tree/master/balena-base-images/python/raspberrypi4-64/ubuntu/focal).

Where can I download these images from or how else should I proceed if I need Python in Focal?

**Comment by nghiant2710** [comment]
Hey @mrts, `balenalib/raspberrypi4-64-python` is debian-based base images (not ubuntu) so you won't be able to find `focal` tag there. Also there is an issue with raspberrypi userland package we install for raspberrypi family base images not available in arm64 ubuntu focal, so you should use the generic arm64 ubuntu base images instead.

Can you please try `balenalib/aarch64-ubuntu-python:3-focal` instead?
