### ISSUE TITLE
 balenalib/rpi-raspbian fails to build on apple silicon Macs.

### ISSUE THREAD

**Issue by cosnicolaou** [balena-io-library/base-images#741]
The following Dockerfile fails with QEMU illegal instruction error when run on an apple silicon Mac.

```
FROM balenalib/rpi-raspbian:bullseye-20210925
USER root
RUN apt-get update -y && apt-get upgrade -y
```

**Comment by builder555** [comment]
Adding ENV QEMU_CPU=max in the dockerfile fixes the issue:
```
FROM balenalib/rpi-raspbian:bullseye-20210925
ENV QEMU_CPU=max
USER root
RUN apt-get update -y && apt-get upgrade -y
```

**Comment by cosnicolaou** [comment]
thanks, that does indeed work. Can you explain why? Thanks again!

**Comment by builder555** [comment]
[This issue](https://github.com/docker/for-mac/issues/5561) mentions that by qemu defaults to "core2duo" cpu, when nothing is specified. I personally, don't understand a lot of it, but what stood out is that enabling all features (i.e. "max") should work every time.

**Comment by cosnicolaou** [comment]
thanks!
