### ISSUE TITLE
xbuild removed

### ISSUE THREAD

**Issue by splitice** [balena-io-library/base-images#782]
The URL `http://resin-packages.s3.amazonaws.com/resin-xbuild/v1.0.0/resin-xbuild1.0.0.tar.gz` is not valid

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>247ZFFK4RGSV31AN</RequestId>
<HostId>tmnXouUJQyXH4wgy52Sw7g96ZkIEgqxv8wCoZXXPIOBakQUmwCjbm2KneouPH1G5iUaHQ6ZuiUY=</HostId>
</Error>
```

i.e file not found

**Comment by nghiant2710** [comment]
@splitice, so sorry for the inconvenience, there is an issue with the access policy for the resource so it is not available atm. I will let you know when it is back.

**Comment by nghiant2710** [comment]
@splitice, it should be fine now, please let us know if the issue still persists.
