### ISSUE TITLE
Docker Hub Docs Request: documenting all supported versions in balenalib/beaglebone-black-python

### ISSUE THREAD

**Issue by jamesbraza** [balena-io-library/base-images#791]
From [balenalib/beaglebone-black-python](https://hub.docker.com/r/balenalib/beaglebone-black-python):

> Supported versions and respective `Dockerfile` links:
> 
> [`2.7.16 (latest)`, `3.7.4`, `3.6.9`, `3.5.7`, `3.4.10`](https://github.com/balena-io-library/base-images/tree/master/balena-base-images/python/beaglebone-black/debian/)

Actually, this doesn't reflect the [manifest's versions](https://github.com/balena-io-library/official-images/blob/master/library/beaglebone-black-debian-python) (e.g. 3.10.5, 3.9.13).

It would be good to sync up the Docker hub page with the currently supported versions.

---

A similar request can be made for [balenalib/beaglebone-black-debian-python](https://hub.docker.com/r/balenalib/beaglebone-black-debian-python).

**Comment by nghiant2710** [comment]
Hey @jamesbraza, we just updated the Docker hub description for the requested repositories. Thank you for the report and please  do not hesitate to let us know if you have further questions.
