### ISSUE TITLE
"Unable to start udev, container must be run in privileged mode to start udev!" error is thrown when a non-root user is defined in the Dockerfile

### ISSUE THREAD

**Issue by thgreasi** [balena-io-library/base-images#871]
When the `USER myuser` docker command is used the Dockerfile and the user doesn't have root permissions, then the UDev check fails and reports a misleading error about the container not being privileged, even if it is.
https://github.com/balena-io-library/base-images/blob/33e70638c22e111855a65fa2e622876e3213ea0f/scripts/assets/entry.sh#L57

**Comment by klutchell** [comment]
Added clarification to the docs: https://github.com/balena-io/docs/pull/2762
